name: Run OpenEO Tests
on:
  repository_dispatch:
    types:
      - test-execute-openeotestsuite

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Create virtual environment
        run: python -m venv venv
      
      - name: Activate virtual environment and install dependencies
        env:
          OPENEO_TOKEN: ${{ secrets.OPENEO_REFRESH_TOKEN }}
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          mkdir -p /home/runner/.local/share/openeo-python-client/
          echo "$OPENEO_TOKEN" > /home/runner/.local/share/openeo-python-client/refresh-tokens.json
          chmod 600 /home/runner/.local/share/openeo-python-client/refresh-tokens.json
      
      - name: Run OpenEO tests
        run: |
          source venv/bin/activate
          python run_tests_and_count.py

      - name: Upload test report as artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports
          path: reports/general.html
